### ISSUE TITLE
Enlightenment for FreeBSD

### ISSUE THREAD

**Issue by cederom** [sambler/sambler-redports#1]
Hello @sambler ! You are the master of FreeBSD ports. Once again thank you for helping with UPBGE! You may also get interested in Enlightenment WM? I am sure you will like it :-) FreeBSD still uses the buggy 0.22 version while there is already new fixed version 0.23.1 but I was not able to make it work and make port out of it. Could you please help me and update the x11-wm/enlightenment port please please please? :-)

https://github.com/Enlightenment/enlightenment

**Comment by sambler** [comment]
I'm no master, just like to give back for what I get to use. Most of it is getting what I want to use working and then sharing that with others.

I did find enlightenment interesting back when I started using FreeBSD for my desktop. Don't recall why I didn't use it but I ended up choosing xfce4 and have had no issues with it in 8 years.

I had a quick look but I'm not installing it to test. I will email you the files to get devel/efl and x11-wm/enlightenment compiling, you may then need to make similar changes to all the other enlightenment apps. If you don't have a jail or bhyve setup to test compile in, then you will break all your e-apps until you get them compiling.
